config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :action_points, except: [:show, :destroy]
  resources :attachments, except: [:show, :destroy]
  resources :dayoffs do
    get :employees, on: :collection
  end
  resources :events, only: :index
  resources :expenses
  resources :notes, except: [:show, :destroy]
  resources :people do
    get :autocomplete_employee_name, on: :collection
    get :autocomplete_person_name, on: :collection
  end
  resources :project_notes, except: [:show, :destroy]
  resources :projects, except: [:destroy] do
    get :autocomplete_project_name, on: :collection
  end


  resources :reports, only: :index do
    collection do
      # get :by_status
      # get :by_technology
      get :current_employees_table
      get :contractors_table
      get :employees_by_birthday_month
      get :employees_by_last_one_on_one_meeting_date
      get :upcoming_performance_review
      get :employees_expenses
      get :employees_history
      get :employees_simple
      get :employees_without_nda_signed
      get :funnel
      get :historical_data
      get :people_with_similar_name
      get :searches
    end
  end
  resources :search, only: :index
  resources :tags, only: :index
  resources :users, except: :destroy
  resources :vacancies, except: :destroy
  namespace :admin do
    resources :companies
  end

  root 'home#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  include ChangesTracker

  attachment :file

  belongs_to :person, counter_cache: true, touch: true

  validates :person, :file, presence: true
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def index
    @q = Attachment.accessible_by(current_ability).ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @attachments = @q.result

    @attachments = @attachments.offset(params.dig(:page, :offset)) if params.dig(:page, :offset).present?
    @attachments = @attachments.limit((params.dig(:page, :limit) || ENV['ITEMS_PER_PAGE']).to_i)

    @attachments = @attachments.includes(:person)

    respond_to do |f|
      f.partial { render partial: 'table' }
      f.html
    end
  end

  def show
    @attachment = Attachment.find(params[:id])
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.new(attachment_params)
    if @attachment.save
      log_event(entity: @attachment, action: 'created')
      @attachment.person.update(created_by_name: current_user.email, updated_by_name: current_user.email)
      redirect_to (session[:return_to] && session[:return_to][request.params[:controller]]) || attachments_path, flash: { success: 'Attachment created' }
    else
      flash.now[:error] = 'Attachment was not created'
      render :new
    end
  end

  def edit
    @attachment = Attachment.accessible_by(current_ability).find(params[:id])
  end

  def update
    @attachment = Attachment.accessible_by(current_ability).find(params[:id])
    if @attachment.update(attachment_params)
      log_event(entity: @attachment, action: 'updated')
      @attachment.person.update(updated_by_name: current_user.email)
      redirect_to (session[:return_to] && session[:return_to][request.params[:controller]]) || attachments_path, flash: { success: 'Attachment updated' }
    else
      flash.now[:error] = 'Attachment was not updated'
      render :edit
    end
  end

private

  def attachment_params
    params.require(:attachment).permit(:person_id, :file, :name, :description)
  end
end

app/views/attachments/_form.slim
= render 'shared/form_error', object: @attachment

= simple_form_for @attachment, html: { class: 'form' } do |f|
  .form-group
    - if defined?(partial_form) && partial_form.present?
      input type="hidden" name="attachment[person_id]" value="#{@person.id}"
    - elsif @attachment.new_record?
      - if params.dig(:attachment, :person_id).blank?
        = f.input :person_id, as: :hidden
        label.control-label
          span.text-danger *
          | Person:&nbsp;
        input.select.form-control value="#{(Person.find_by_id(params.dig(:attachment, :person_id)) || @attachment.person)&.name}" type="text" data-autocomplete="#{autocomplete_person_name_people_path}" data-id-element="#attachment_person_id" data-auto-focus="true"
      - else
        = f.input :person_id, as: :hidden, input_html: {value: params[:attachment][:person_id]}
        label.control-label
          span.text-danger *
          | Person:&nbsp;
        a href="#{person_path(Person.find_by_id(params.dig(:attachment, :person_id)))}" #{(Person.find_by_id(params.dig(:attachment, :person_id))).name}
    - else
      label.control-label Person&nbsp;
      a href="#{person_path(@attachment.person)}" #{@attachment.person.name}

  .form-group
    label.control-label
      | File
      span.text-danger *
    - if @attachment.file.present?
      = link_to 'Download', Refile.attachment_url(@attachment, :file)
    - else
      | No file to display
    br
    = f.attachment_field :file, label: false, class: 'input form-control'
  .form-group
    label.control-label
      | Name
    = f.input :name, placeholder: 'Friendly name', label: false, class: 'input form-control'
  .form-group
    label.control-label
      | Description
    = f.input :description, as: :text, placeholder: 'About this file', label: false, input_html: { rows: (defined?(partial_form) && partial_form.present?) ? 1 : 3 }

  .form-bordered
    .form-group.form-actions
      .text-center
        = f.button :submit, (@attachment.new_record? ? 'Create Attachment' : 'Update Attachment'), class: 'btn btn-success'

app/views/attachments/_table.slim
- if @attachments.empty?
  span class='js-page-last'

- @attachments.each_with_index do |record, index|
  - if !(record.name.presence || record.file_filename).include?('offer') || ((record.name.presence || record.file_filename).include?('offer') && current_user.has_access_to_finances?)
    tr class=('js-page-last' if (index == @attachments.size - 1) && last_page?(@attachments))
      td
        = link_to record.person.name, person_path(record.person)
        - if record.person.primary_tech.present?
          br
          = link_to record.person.primary_tech, people_path(q: {primary_tech_eq: record.person.primary_tech})
      td = record.name
      td = with_newlines(record.description)
      td = link_to 'Download', Refile.attachment_url(record, :file)
      td = number_to_human_size(record.file_size)
      td = record.created_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
      td
        = record.updated_at.strftime(t(:datetime_full))
        br
        = record.updated_by_name&.split('@')&.first
      td
        a.btn.btn-sm.btn-info.btn-pill href="#{edit_attachment_path(record)}"
          i.fa.fa-pencil
          | &nbsp; Edit

app/views/attachments/edit.slim
h2.title Edit Attachment for #{@attachment.person.name}

= render 'form'

app/views/attachments/index.slim
h2.title
  | ATTACHMENTS &nbsp;
  a.btn.btn-default.btn-pill href="/attachments/new"
    i.fa.fa-plus
    | &nbsp; Add attachment


table.table.pretty-table
  thead
    th = sort_link @q, :person, ['person_name'], 'Person'
    th = sort_link @q, :name
    th = sort_link @q, :description
    th File
    th = sort_link @q, :file_size, 'Size'
    th = sort_link @q, :created_at, 'Created'
    th = sort_link @q, :updated_at, 'Updated'
    th Actions
  tbody.js-loadable-list
    = render 'table'

= render 'shared/load_button', collection: @attachments

app/views/attachments/new.slim
h2.title New Attachment

= render 'form'