config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :action_points, except: [:show, :destroy]
  resources :attachments, except: [:show, :destroy]
  resources :dayoffs do
    get :employees, on: :collection
  end
  resources :events, only: :index
  resources :expenses
  resources :notes, except: [:show, :destroy]
  resources :people do
    get :autocomplete_employee_name, on: :collection
    get :autocomplete_person_name, on: :collection
  end
  resources :project_notes, except: [:show, :destroy]
  resources :projects, except: [:destroy] do
    get :autocomplete_project_name, on: :collection
  end


  resources :reports, only: :index do
    collection do
      # get :by_status
      # get :by_technology
      get :current_employees_table
      get :contractors_table
      get :employees_by_birthday_month
      get :employees_by_last_one_on_one_meeting_date
      get :upcoming_performance_review
      get :employees_expenses
      get :employees_history
      get :employees_simple
      get :employees_without_nda_signed
      get :funnel
      get :historical_data
      get :people_with_similar_name
      get :searches
    end
  end
  resources :search, only: :index
  resources :tags, only: :index
  resources :users, except: :destroy
  resources :vacancies, except: :destroy
  namespace :admin do
    resources :companies
  end

  root 'home#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def by_status
  end

  def by_technology
    respond_to do |format|
      format.html
      format.xlsx do
        people = Person.not_deleted.accessible_by(current_ability).where(primary_tech: params[:primary_tech])

        Axlsx::Package.new do |p|
          p.use_shared_strings = true
          wb = p.workbook
          wb.add_worksheet(name: params[:primary_tech].gsub(/[^a-zA-Z\s0-9]+/, '-')) do |sheet|
            sheet.add_row [
              'Name',
              'HR Status',
              'City',
              'Email',
              'Skype',
              'Phone',
              'Notes']
            people.each do |item|
              notes = item.notes.accessible_by(current_ability).order(updated_at: :desc).map do |note|
                if !note.type.in?(Note::FINANCE_TYPES) || (note.type.in?(Note::FINANCE_TYPES) && current_user.has_access_to_finances?)
                  [
                    note.created_at.strftime(t(:day)),
                    note.value
                  ].join("\r\n".html_safe)
                end
              end.join("\r\n---------------\r\n".html_safe)
              sheet.add_row [
                item.name,
                item.status,
                item.city,
                item.email,
                item.skype,
                "'#{item.phone}",
                notes
              ]
            end
            send_data p.to_stream().read, filename: "#{params[:primary_tech].underscore}.xlsx"
          end
        end
      end
    end
  end

  def contractors_table
    @people = Person.not_deleted.accessible_by(current_ability).where(status: 'Contractor').order(:name)
  end

  def employees_without_nda_signed
    load_current_employees
    unless params[:show_all] == 'true'
      @people = @people
        .where(signed_nda: false)
        .where('start_date < ?', Time.zone.now.strftime('%F'))
    end
  end

  def employees_by_birthday_month
    load_current_employees
    @people_table = @people
      .map { |p| [p.id, p.name, p.day_of_birth&.strftime('%d %b'), p.day_of_birth&.strftime('%m-%d') || '99-99'] }
      .sort { |a, b| a[3].to_s <=> b[3].to_s }

    respond_to do |format|
      format.html
      format.xlsx do
        Axlsx::Package.new do |p|
          p.use_shared_strings = true
          wb = p.workbook
          wb.add_worksheet(name: 'Employee Birthdays') do |sheet|
            sheet.add_row %w(Date Name)

            current_month = nil
            @people_table.each do |record|
              if record[2].present? && current_month != record[2].split(' ').last
                current_month = record[2].split(' ').last
                sheet.add_row [record[2].split(' ').last, '']
              end

              sheet.add_row [record[2], record[1]]
            end
          end

          send_data p.to_stream().read, filename: "birthdays-#{Time.zone.now.strftime('%F')}.xlsx"
        end
      end
    end
  end

  def current_employees_table
    load_current_employees

    respond_to do |format|
      format.html
      format.xlsx do
        Axlsx::Package.new do |p|
          p.use_shared_strings = true
          wb = p.workbook
          wb.add_worksheet(name: 'Employees') do |sheet|
            sheet.add_row [
              'Name',
              'Date of Birth',
              'Starting Date',
              'City',
              'Email',
              'Skype',
              'Phone',
              'Position']
            @people.each do |item|
              sheet.add_row [
                item.name,
                (item.day_of_birth.present? ? item.day_of_birth.strftime(t(:for_csv)) : 'n/a'),
                (item.start_date.present? ? item.start_date.strftime(t(:for_csv)) : 'n/a'),
                item.city,
                item.email,
                item.skype,
                "'#{item.phone}",
                item.current_position
              ]
            end
          end
          send_data p.to_stream().read, filename: "colleagues-#{Time.zone.now.strftime('%F')}.xlsx"
        end
      end
    end
  end

  def current_employees_technical
    load_current_employees
  end

  def employees_expenses
    load_current_employees
  end

  def employees_history
    @people = Person.not_deleted.accessible_by(current_ability)
      .where(status: ['Hired', 'Past employee'])
      .order(:start_date)
    @people_table = @people
      .map { |p| [p.id, p.name, p.start_date&.strftime('%Y-%m'), p.start_date&.strftime('%e %b %Y'), p.finish_date&.strftime('%e %b %Y')] }
      .sort { |a, b| a[2].to_s <=> b[2].to_s } # technical field
  end

  def people_with_similar_name
    @people = SimilarsCollector.new.perform
  end

  def historical_data
    @data = HistoricalDataCollector.new.perform
  end

  def employees_simple
    load_current_employees
  end

  def employees_by_last_one_on_one_meeting_date
    load_current_employees
    @people = @people
      .where('city ILIKE ?', ENV['MAIN_CITY'])
      .where('start_date < ?', Time.zone.now.strftime('%F'))
      .reorder('last_one_on_one_meeting_at IS NOT NULL, last_one_on_one_meeting_at ASC')
      .order(:name)
  end

  def upcoming_performance_review
    # set default params. may be moved to service
    params[:performance_review] = {
      start_date: 10.years.ago.beginning_of_year.strftime('%d-%m-%Y'),
      finish_date: 1.month.since.strftime('%d-%m-%Y'),
      order: 'next_review'
    } if params[:performance_review].blank?

    if performance_review_params[:start_date].present? &&
      performance_review_params[:finish_date].present? &&
      Time.strptime(performance_review_params[:start_date], '%d-%m-%Y') > Time.strptime(performance_review_params[:finish_date], '%d-%m-%Y')
      params[:performance_review][:start_date], params[:performance_review][:finish_date] = performance_review_params[:finish_date], performance_review_params[:start_date]
    end

    service = PerformanceReviewStatsCollector.new(
      start_date: performance_review_params[:start_date],
      finish_date: performance_review_params[:finish_date],
      order: performance_review_params[:order]
    )
    service.perform
    @people = service.scope
    params[:performance_review][:start_date] = service.start_date
    params[:performance_review][:finish_date] = service.finish_date
  end

  def funnel
    params[:funnel] = {
      start_date: Time.zone.now.beginning_of_week.strftime('%d-%m-%Y'),
      finish_date: Time.zone.now.end_of_week.strftime('%d-%m-%Y'),
      user_email: '',
    } if params[:funnel].blank?
    params[:funnel][:start_date] = Time.zone.now.beginning_of_week.strftime('%d-%m-%Y') if params[:funnel][:start_date].blank?
    params[:funnel][:finish_date] = Time.zone.now.end_of_week.strftime('%d-%m-%Y') if params[:funnel][:finish_date].blank?
    if params[:funnel][:start_date].present? &&
      params[:funnel][:finish_date].present? &&
      Time.strptime(params[:funnel][:start_date], '%d-%m-%Y') > Time.strptime(params[:funnel][:finish_date], '%d-%m-%Y')
      params[:funnel][:start_date], params[:funnel][:finish_date] = params[:funnel][:finish_date], params[:funnel][:start_date]
    end

    @vacancies = Vacancy
    if funnel_update_params[:vacancy_id].present?
      @vacancies = @vacancies.where(id: funnel_update_params[:vacancy_id])
    else
      @vacancies = @vacancies.where(status: 'open')
    end
    @vacancies = @vacancies.order(:created_at)

    @funnel = FunnelStatsCollector.new(
      scope: Person.accessible_by(current_ability).not_deleted,
      vacancies: @vacancies,
      start_date: funnel_update_params[:start_date],
      finish_date: funnel_update_params[:finish_date],
      user_email: funnel_update_params[:user_email]
    ).perform

    if params['xlsx'].present?
      Axlsx::Package.new do |p|
        p.use_shared_strings = true
        wb = p.workbook
        wb.add_worksheet(name: 'Funnel') do |sheet|
          sheet.add_row [
            'Vacancy',
            'Created candidates',
            'Touched candidates',
            'No status',
            'Not interested or rejected',
            'Interested',
            'Interview process',
            'Passed Interview',
            'Hired',
            'Source',
            'Updated By'
          ]

          @funnel.each do |item|
            sheet.add_row [
              item[:vacancy_title],
              item[:people_created],
              item[:people_updated_count],
              item[:people_no_status_count],
              item[:people_not_interested_count],
              item[:people_interested_count],
              item[:people_interview_count],
              item[:people_passed_interview_count],
              item[:people_hired_count],
              item[:sources].map { |i| "#{i[1]} #{i[0]}" }.join("\r\n"),
              item[:updates].map { |i| "#{i[:count]} #{i[:name]}" }.join("\r\n")
            ]
          end
        end
        send_data p.to_stream().read, filename: "funnel--#{funnel_update_params[:start_date]}--#{funnel_update_params[:finish_date]}.xlsx"
        return
      end
    end
  end

  private

  def load_current_employees
    @people = Person.not_deleted.accessible_by(current_ability)
      .current_employee
      .order(:name)
  end

  def funnel_update_params
    params.require(:funnel).permit(:start_date, :finish_date, :user_email, :vacancy_id)
  end

  def performance_review_params
    params.require(:performance_review).permit(:start_date, :finish_date, :order)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def expenses_stats_per_year(person_id)
    service = ExpensesStatsCollector.new(person_id: person_id)
    service.perform
    service.stats
  end
end

app/views/reports/_vacancy_candidates_by_status.slim
table.table style="margin-top: -8px; width: 300px"
  tbody
    - vacancy_candidates_by_status(vacancy).each_pair do |status, count|
      tr
        td
          span style="width: 10px; background-color: #{PERSON_STATUS_COLORS[status]};" &nbsp;&nbsp;&nbsp;&nbsp;
          | &nbsp;
          = link_to status, vacancy_path(vacancy, q: { status_eq: status })
        td width="50px"
          = link_to count, vacancy_path(vacancy, q: { status_eq: status })

app/views/reports/by_status.slim
h2.title People by status

table.table.pretty-table
  thead
    th Status
    th People
  tbody
    - PERSON_STATUS_COLORS.each_pair do |status, color|
      tr
        td
          span style="width: 10px; background-color: #{color};" &nbsp;&nbsp;&nbsp;&nbsp;
          | &nbsp;
          = link_to status, people_path(q: { status_eq: status })
        td
          = link_to Person.not_deleted.accessible_by(current_ability).where(status: status).count, people_path(q: { status_eq: status })

app/views/reports/by_technology.slim
h2.title People by Technology

table.table.pretty-table
  thead
    th Tech
    th People
    th Employees
    th Actions
  tbody
    - Person::PRIMARY_TECHS.each_with_index do |tech, index|
      tr
        td
          span style="width: 10px; background-color: #{PERSON_STATUS_COLORS.values[index]};" &nbsp;&nbsp;&nbsp;&nbsp;
          | &nbsp;
          = link_to tech, people_path(q: { primary_tech_eq: tech })
        td
          = link_to Person.not_deleted.accessible_by(current_ability).where(primary_tech: tech).count, people_path(q: { primary_tech_eq: tech })
        td
          = link_to Person.not_deleted.accessible_by(current_ability).current_employee.where(primary_tech: tech).count, people_path(q: { primary_tech_eq: tech, status_eq: 'Hired' })
        td
          = link_to 'Export to XLSX', by_technology_reports_path(format: :xlsx, primary_tech: tech)

app/views/reports/contractors_table.slim
h2.title Contractors Table
= link_to 'Show technical info', contractors_table_reports_path(show_technical: 'true')
br
= "#{@people.count} contractors"

table.table.pretty-table
  thead
    th #
    th Name
    th Birth
    th Start Date
    th City
    th Email
    th Skype
    th Phone
    th Position
    - if params[:show_technical].present?
      th Signed NDA?
  tbody
    - @people.each_with_index do |person, index|
      tr
        td
          span style="width: 10px; background-color: #{PERSON_STATUS_COLORS[person.status]};" &nbsp;#{index + 1}&nbsp;
        td
          = link_to person.name, person_path(person.id)
        td
          - if person.day_of_birth.present?
            = person.day_of_birth.strftime(t(:datetime_full)).gsub('00:00, ', '')
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.start_date.present?
            = person.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.city.present?
            = person.city
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.email.present?
            = person.email
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.skype.present?
            = person.skype
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.phone.present?
            = person.phone
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.current_position.present?
            = person.current_position
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        - if params[:show_technical].present?
          td
            - if person.signed_nda?
              = 'yes'
            - else
              a href="#{edit_person_path(person)}"
                i.fa.fa-pencil

app/views/reports/current_employees_table.slim
h2.title Current Employees Table
= link_to 'Show Past Employees', people_path(q: { status_in: Person::PAST_EMPLOYEE_STATUSES })
br
= link_to 'Export to XLSX', current_employees_table_reports_path(format: :xlsx)
br
= "#{@people.count} employees"

table.table.pretty-table
  thead
    th #
    th ID
    th Name
    th Birth
    th Start Date
    th City
    th Email
    th Skype
    th Phone
    th Position
  tbody
    - @people.each_with_index do |person, index|
      tr
        td
          span style="width: 10px; background-color: #{PERSON_STATUS_COLORS[person.status]};" &nbsp;#{index + 1}&nbsp;
        td
          = person.employee_id
        td
          = link_to person.name, person_path(person.id)
        td
          - if person.day_of_birth.present?
            = person.day_of_birth.strftime(t(:datetime_full)).gsub('00:00, ', '')
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.start_date.present?
            - if person.start_date > Time.zone.now
              strong
                = person.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')
            - else
              = person.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.city.present?
            = person.city
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.email.present?
            - if !ENV['COMPANY_EMAIL_MASK'].in?(person.email)
              span style="color: red"
                = person.email
            - else
              = person.email
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.skype.present?
            = person.skype
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.phone.present?
            = person.phone
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil
        td
          - if person.current_position.present?
            = person.current_position
          - else
            a href="#{edit_person_path(person)}"
              i.fa.fa-pencil

app/views/reports/employees_by_birthday_month.slim
h2.title Current Employees Birthdays Table
br
= link_to 'Export to XLSX', employees_by_birthday_month_reports_path(format: :xlsx)

table.table.pretty-table
  thead
    th Birth
    th Name
  tbody
    - current_month = nil
    - @people_table.each do |record|
      - if record[2].present? && current_month != record[2].split(' ').last
        - current_month = record[2].split(' ').last
        tr
          th colspan="2" = record[2].split(' ').last
      tr
        td
          - if record[2].present?
            = record[2]
          - else
            a href="#{edit_person_path(record[0])}"
              i.fa.fa-pencil
        td = link_to record[1], person_path(record[0])

app/views/reports/employees_expenses.slim
h2.title Current Employees expenses
br

table.table.pretty-table
  thead
    th #
    th Name
    th Total
    th Period Info
    th Period Total
    th Period Remainig
    - Expense::TYPES.each do |type|    
      th = type
  tbody
    - @people.each_with_index do |record, index|
      tr
        td
          = index + 1
        td width="200"
          = link_to record.name, person_path(record)
          '
          a href="#{edit_person_path(record)}"
            i.fa.fa-pencil
          - if record.start_date.present?
            br
            = record.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')
            br
            - if record.start_date.present? && record.start_date > Time.zone.now
              'not started
            - else
              sub = "#{months_worked(record) > 0 ? pluralize(months_worked(record), 'month') : 'just started'}"
        td
          - if record.start_date.present? && record.start_date <= Time.zone.now
            - total_expenses = record.expenses.sum(:amount)
            - if total_expenses > 0 && total_expenses >= (ENV['EXPENSES_LIMIT_PER_YEAR'].to_i / 12) * months_worked(record)
              span style="color: red"
                strong
                  = total_expenses
            - else
              = total_expenses

        - if record.start_date.present? && record.start_date <= Time.zone.now
          - expenses_stats_per_year(record.id).tap do |stats|
            - stats[stats.keys.last].tap do |stat|
              - if stat.present?
                td
                  = stat['period_start_date'].gsub(/\s/, '&nbsp;').html_safe
                  br
                  | to
                  br
                  = stat['period_end_date'].gsub(/\s/, '&nbsp;').html_safe
                  br
                  = "#{(stat['year'] + 1).to_i.ordinalize} year"
                td
                  - if stat['total_expenses'] >= ENV['EXPENSES_LIMIT_PER_YEAR'].to_i
                    span style="color: red"
                      strong
                        = stat['total_expenses']
                  - else
                    = stat['total_expenses']
                td
                  - if stat['remaining_expenses'] < ENV['EXPENSES_LIMIT_PER_YEAR'].to_i / 12
                    span style="color: red"
                      strong
                        = stat['remaining_expenses']
                  - elsif stat['remaining_expenses'] == ENV['EXPENSES_LIMIT_PER_YEAR'].to_i
                    span style="color: green"
                      strong
                        = stat['remaining_expenses']
                  - else
                    = stat['remaining_expenses']
                - Expense::TYPES.each do |type|
                  td
                    = stat['total_expenses_by_type'][type]

app/views/reports/employees_without_nda_signed.slim
h2.title Current Employees without NDA signed
= "#{@people.count} employees did not sign"
br
= link_to 'show all', employees_without_nda_signed_reports_path(show_all: 'true')

table.table.pretty-table
  thead
    th Name
    - if params[:show_all] == 'true'
      th NDA Signed?
    th Files
  tbody
    - @people.each_with_index do |person|
      tr
        td
          = link_to person.name, person_path(person)
          '&nbsp;
          a href="#{edit_person_path(person)}"
            i.fa.fa-pencil
        - if params[:show_all] == 'true'
          td
            = person.signed_nda? ? 'yes' : ''
        td
          - person.attachments.each do |attachment|
            - if !(attachment.name.presence || attachment.file_filename).include?('offer') || ((attachment.name.presence || attachment.file_filename).include?('offer') && current_user.has_access_to_finances?)
              = link_to attachment.name, Refile.attachment_url(attachment, :file)
              '&nbsp;

app/views/reports/funnel.slim
h2.title Funnel Report
= link_to "#{@vacancies.count} open vacancies", vacancies_path(q: { status_eq: 'open' })

= simple_form_for :funnel, html: { method: :get, class: 'form' } do |f|
  label.control-label From&nbsp;

  = link_to 'today', funnel_reports_path(funnel: { start_date: Time.zone.now.strftime('%d-%m-%Y'), finish_date: 1.day.since.strftime('%d-%m-%Y') })
  ',
  = link_to 'current week', funnel_reports_path
  ',
  = link_to 'past and current week', funnel_reports_path(funnel: { start_date: (Time.zone.now - 7.days).beginning_of_week.strftime('%d-%m-%Y'), finish_date: Time.zone.now.end_of_week.strftime('%d-%m-%Y') })

  = f.input :start_date, as: :string, placeholder: 'dd-mm-yyyy', label: false, input_html: { value: params[:funnel][:start_date], class: 'datepicker', autocomplete: 'off' }
  label.control-label to &nbsp;
  = f.input :finish_date, as: :string, placeholder: 'dd-mm-yyyy', label: false, input_html: { value: params[:funnel][:finish_date], class: 'datepicker', autocomplete: 'off' }

  div.form-group
    label.control-label Updated by user:
    select.select.form-control name="funnel[user_email]"
      option value=""
      - User.order(:email).each do |user|
        - if params[:funnel] && params[:funnel][:user_email].presence == user.email
          option value="#{user.email}" selected="selected" #{user.email}
        - else
          option value="#{user.email}" #{user.email}

  = f.button :submit, 'View Report', class: 'btn btn-success'
  '&nbsp;
  = f.button :submit, 'Export to XLSX', name: 'xlsx', value: 'Export to XLSX', class: 'btn btn-success'

table.table.pretty-table
  thead
    th Vacancy
    th Created candidates
    th Touched candidates
    th
      'No status
      br
      sub = FunnelStatsCollector::NO_STATUS_STATUSES.join(', ')
    th
      'Not interested or rejected
      br
      sub = FunnelStatsCollector::NOT_INTERESTED_STATUSES.join(', ')
    th
      'Interested
      br
      sub = FunnelStatsCollector::INTERESTED_STATUSES.join(', ')
    th
      'Interview process
      br
      sub = FunnelStatsCollector::INTERVIEW_STATUSES.join(', ')
    th
      'Passed Interview
      br
      sub = FunnelStatsCollector::PASSED_INTERVIEW_STATUSES.join(', ')
    th
      'Hired
      br
      sub = FunnelStatsCollector::HIRED_STATUSES.join(', ')
    th Source
    th Updated By
  tbody
    - @funnel.each do |item|
      - finish_date = (Time.strptime(params[:funnel][:finish_date], '%d-%m-%Y') + 1.day).strftime('%Y-%m-%d')
      tr
        td = link_to item[:vacancy_title], vacancy_path(item[:vacancy_id])
        td = link_to item[:people_created], people_path(q: { created_at_gteq: params[:funnel][:start_date], created_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]] })
        td = link_to item[:people_updated_count], people_path(q: { updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]] })
        td = link_to item[:people_no_status_count], people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], status_in: FunnelStatsCollector::NO_STATUS_STATUSES })
        td = link_to item[:people_not_interested_count], people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], status_in: FunnelStatsCollector::NOT_INTERESTED_STATUSES })
        td = link_to item[:people_interested_count], people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], status_in: FunnelStatsCollector::INTERESTED_STATUSES })
        td = link_to item[:people_interview_count], people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], status_in: FunnelStatsCollector::INTERVIEW_STATUSES })
        td = link_to item[:people_passed_interview_count], people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], status_in: FunnelStatsCollector::PASSED_INTERVIEW_STATUSES })
        td = link_to item[:people_hired_count], people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], status_in: FunnelStatsCollector::HIRED_STATUSES })
        td
          - item[:sources].each_pair do |source, count|
            - source_hash = source == 'n/a' ? { source_blank: '1' } : { source_eq: source }
            = link_to "#{count}&nbsp;#{source}".html_safe, people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]]}.merge(source_hash))
            br
        td
          - item[:updates].each do |update|
            = link_to "#{update[:count]}&nbsp;#{update[:name]}".html_safe, people_path(q: {updated_at_gteq: params[:funnel][:start_date], updated_at_lteq: finish_date, by_tag_including: [item[:vacancy_tag]], updated_by_name_eq: update[:by_name]})
            br

app/views/reports/upcoming_performance_review.slim
h2.title Upcoming Performance Reviews

= link_to 'show current month', upcoming_performance_review_reports_path
br

= simple_form_for :performance_review, html: {method: :get, class: 'form'} do |f|
  label.control-label Next review from&nbsp;
  = f.input :start_date, as: :string, placeholder: 'dd-mm-yyyy', label: false, input_html: { value: params[:performance_review][:start_date], class: 'datepicker', autocomplete: 'off' }
  label.control-label Next review to &nbsp;
  = f.input :finish_date, as: :string, placeholder: 'dd-mm-yyyy', label: false, input_html: { value: params[:performance_review][:finish_date], class: 'datepicker', autocomplete: 'off' }

  = f.input :order, as: :select, collection: %w(next_review last_review), include_blank: false, selected: params[:performance_review][:order]

  = f.button :submit, 'View Report', class: 'btn btn-success'
br
= "#{@people.count} employees"
br
span style="color: grey"
  strong
    | grey color&nbsp;
| - next review date in the future
br
span style="color: red"
  strong
    | red color&nbsp;
| - last review date is less than 6 months

table.table.pretty-table
  thead
    th Name
    th Next Review Planned
    th Last Review
    th Start Date
  tbody
    - @people.each do |record|
      tr
        td = link_to record.name, person_path(record)
        td
          - if record.next_performance_review_at.present?
            - if record.next_performance_review_at >= Time.zone.now
              span style="color: grey"
                strong
                  = record.next_performance_review_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
            - else
              = record.next_performance_review_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
          - else
            a href="#{edit_person_path(record)}"
              i.fa.fa-pencil
        td
          - if record.last_performance_review_at.present?
            - if record.last_performance_review_at >= 6.months.ago
              span style="color: red"
                strong
                  = record.last_performance_review_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
            - else
              = record.last_performance_review_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
          - else
            a href="#{edit_person_path(record)}"
              i.fa.fa-pencil
        td = record.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')